### PR TITLE
refactor: canvas nutmeg migration (removed migrated assets to plugin)

### PR DESCRIPTION
**Pull request by arslanashraf7**
## Related ticket:
https://github.com/mitodl/edx-platform/issues/296

## What this PR does?
- Refactors the cherry-pick commit for nutmeg
- Removes the parts that are now moved to the plugin in https://github.com/mitodl/open-edx-plugins/pull/54

## Testing instructions:
- Setup the platform on this branch
- Now install the Canvas plugin from https://github.com/mitodl/open-edx-plugins/pull/54
- Make sure that the plugin's functionality is working fine (You can take a look at the plugin Readme for how to test plugin functionality)

## Background context:
- The details are mentioned in the associated ticket above

### CODE REVIEW

**Comment by blarghmatey** [comment]
This seems reasonable to me

**Comment by blarghmatey** [comment]
:+1:

**Comment by arslanashraf7** [comment]
@blarghmatey Since I've merged the Nutmeg migrations PRs in plugins I have a couple of questions to take your assistance upon:

1) Are we running our https://github.com/mitodl/edx-platform/tree/mitx/nutmeg branch on prod?
2) For the two cherry-picks(Canvas, Rapid Response) on https://github.com/mitodl/edx-platform/tree/mitx/nutmeg what is your preference (to remove them) because the rapid response commit won't be needed after plugin migration and the canvas commit will be updated.
     - _Option1_: Trim those commits and just merge this PR.
     - _Option2_: Create another PR that just reverts the rapid response commit, rebase this PR and remove the unneeded code for Canvas? (This will leave us with two commits to cherry-pick for Canvas in the future.)

**Comment by blarghmatey** [comment]
1. We are not currently running nutmeg on production yet, it is only being tested in a CI environment currently.
2. I would suggest that we get rid of the two cherry picks in favor of using the code that is in the plugins and this PR so that we are only tracking commits that we _actually_ need and care about. Thanks for asking!

**Comment by arslanashraf7** [comment]
@blarghmatey There were three things I wanted to discuss & get your opinion regarding this PR and related stuff so that this can be tested:

- Have we deployed new packages for [ol-openedx-rapid-response-reports](https://github.com/mitodl/open-edx-plugins/tree/main/src/ol_openedx_rapid_response_reports) & [ol-openedx-canvas-integration](https://github.com/mitodl/open-edx-plugins/tree/main/src/ol_openedx_canvas_integration).
    - A related thing is if we publish these new packages containing Nutmeg migration, would they affect the production e.g. getting picked in the production build which isn't currently on Nutmeg? In this case, what would we need to do to make sure that our instances with Nutmeg only use these versions?
- Based on above point, we will then need to rebuild our CI instance where we are currently running Nutmeg so that it picks the latest packages and the commit in this PR.

**Comment by blarghmatey** [comment]
The packages have been uploaded to PyPI and the newest build of the residential CI deployment has them included.

If we want to prevent the QA and production instances from picking up the new plugins then we can pin them or remove them as appropriate in the [group_data](https://github.com/mitodl/ol-infrastructure/blob/main/src/bilder/images/edxapp/group_data/all.py) file. We have a branch of the ol-infrastructure repo for tracking Nutmeg related changes, so we can keep the desired change there until we go to production with it.

**Comment by arslanashraf7** [comment]
Thanks for the insights.


>The packages have been uploaded to PyPI and the newest build of the residential CI deployment has them included.

When I search for them on the PyPI they show older versions though e.g. for [rapid-response reports it shows 0.1.0](https://pypi.org/project/ol-openedx-rapid-response-reports/) & for [canvas integration it shows 0.1.1](https://pypi.org/project/ol-openedx-canvas-integration/) which should be `0.2.0` for both.


>If we want to prevent the QA and production instances from picking up the new plugins then we can pin them or remove them as appropriate in the [group_data](https://github.com/mitodl/ol-infrastructure/blob/main/src/bilder/images/edxapp/group_data/all.py) file

I think we should pin them to production config at least so that it doesn't pick the new versions on any rebuild until we specify it in group data to pick the newer ones. I'll create a PR for that.

**Comment by blarghmatey** [comment]
I'll pull and publish those packages again now. I was out of sync with where we are at currently.

**Comment by blarghmatey** [comment]
All of the packages are now up to date

**Comment by arslanashraf7** [comment]
Thanks! Yes and apologies it got sidetracked a little with other work going on. That's why i wanted to get it tested before it's vastly out of context.

So, for pinning the packages in production is it okay that I create the PR in ol-infra tomorrow. I suppose we don't have a plan to rebuild the production at least today.

**Comment by blarghmatey** [comment]
Yeah, we don't have any plans for builds/deploys to production

**Comment by arslanashraf7** [comment]
@blarghmatey I've created [this PR](https://github.com/mitodl/ol-infrastructure/pull/842) to pin the packages.

In addition, the plugin tabs are not showing on [our ci instance](https://lms-ci.mitx.mit.edu/courses/course-v1:MITx+maple1+2021_Fall/instructor#view-course_info) and this could be because of the assets now being compiled. We faced a similar issue when we initially deployed a plugin and that conversation is [here](https://mitodl.slack.com/archives/G72L6SNHH/p1640093947033900). If the latest plugins are installed and the platform has this PR deployed we might just need to recompile the assets.

**Comment by blarghmatey** [comment]
The Nutmeg images were failing to build for a few days because of upstream issues with Node 16. That is now resolved and I rebuilt and deployed the latest image. Also, the assets are being recompiled by default as part of the build so that shouldn't be an issue for this situation.

I don't see a tab for Canvas at the link that you provided, but I'm also not certain what I should be looking for.

**Comment by pdpinch** [comment]
I don't see the Canvas tab on the Instructor Dashboard either. 

I thought maybe it was because the canvas course ID wasn't set in the course's [advanced settings](https://studio-ci.mitx.mit.edu/settings/advanced/course-v1:MITx+maple1+2021_Fall), so I set it to our test course (155), but I'm still not seeing the tab on the instructor dashboard. 

I'm not sure how it's possible to have the advanced setting, but not the instructor dashboard tab.

**Comment by arslanashraf7** [comment]
I was looking around and testing the things locally and it looks like the plugins might not be installed. The probable issues could be like:
1- If the plugin is not installed the (`Canvas`, `Rapid Responses`)tab won't show
2- If the plugins are installed but the path of the template isn't resolvable the Tabs would show but give errors complaining about templates unavailability.

In addition, where can we see the config for CI instance, [In group-data](https://github.com/mitodl/ol-infrastructure/blob/main/src/bilder/images/edxapp/group_data/all.py#L48-L73) there are configs for staging and prod.

**Comment by arslanashraf7** [comment]
Update/FYI, With the new release of Canvas plugin as per https://github.com/mitodl/open-edx-plugins/pull/60 it worked, The Canvas tab is not visible when `canvas_course_id` is set in course advanced settings through the studio.

I've set up the course outlines for [Canvas Test Course](https://lms-ci.mitx.mit.edu/courses/course-v1:MITx+canvas_1+2022_Summer/instructor#view-canvas_integration) for the testing purposes for anyone who wants to play around it.

**Pull request merged**
