### PR TITLE
First release of MITx based on open-release/eucalyptus.2

### PR DESCRIPTION
**Pull request by blarghmatey**
This is the branch that will be deployed to the RP environment for residential MITx.

### CODE REVIEW

**Comment by shaidar** [comment]
:thumbsup:

**Comment by shaidar** [comment]
Is there a PR for this [commit](https://github.com/mitodl/edx-platform/pull/1/commits/b1dbd14b7a074b2b5ee8e21baec0559c9eafc6dd) in the main edx branch?

**Comment by blarghmatey** [comment]
There is, but they closed it because they hadn't duplicated the bug. It's still pending review which means that it will probably never be merged. Probably worth popping back in on the discussion thread to say that it's still a problem.

**Comment by shaidar** [comment]
:thumbsup:

**Comment by blarghmatey** [comment]
We are not going to be deploying Eucalyptus. Closing.

**Pull request closed without merging**
