### PR TITLE
Studio: hide signup button

### PR DESCRIPTION
**Pull request by annagav**
Fix mitodl/mitx-theme#21

### CODE REVIEW

**Comment by amir-qayyum-khan** [comment]
please use cms.env.json file for this configuration

**Comment by amir-qayyum-khan** [comment]
I think it is a @mitodl/devops task.

cc @shaidar @blarghmatey

**Comment by blarghmatey** [comment]
Yes, this is a flag that we can override during deploy. I've added a pillar entry to handle setting the appropriate feature and deployed it to QA.

**Comment by pdpinch** [comment]
Sigh. How many of these "theme" issues are actually configuration issues?

**Pull request closed without merging**
