### PR TITLE
MITx Residential Dogwood Release 3

### PR DESCRIPTION
**Pull request by blarghmatey**
Commits for the third release of the edX platform for Residential MITx.

*Changes*
- Update `compute_grades` command to work with Django 1.8
- Improve error logging for codejail

### CODE REVIEW

**Comment by pdpinch** [comment]
👍

**Comment by shaidar** [comment]
:thumbsup:

**Comment by shaidar** [comment]
:thumbsup:

**Comment by blarghmatey** [comment]
Closing this PR because the MathJax changes have already been included and the codejail change wasn't verified yet

**Pull request closed without merging**
