### PR TITLE
Sysadmin: Only show gitlogs for non superuser

### LINKED ISSUE #136: Sysadmin panel: Hide Users/Courses/Staffing links from non-superusers
We allow instructors to view the gitlogs for their course, so they can see if there were any issues with importing from git. 

However, this view includes links to other sysadmin panel features that instructors don't have permission to access (like loading courses). These links currently throw a 500 when an instructor clicks on them. 

The links should be hidden for users who can't access them. 

screenshot 2019-05-22 11 24 04

#### related issue:

https://github.mit.edu/mitx/Summer-2019/issues/6

### PR DESCRIPTION
**Pull request by annagav**
Fix  #136

If you are not a superuser, when you go to sysadmin dashboard, all you will be able to see is gitlogs.

### CODE REVIEW

**Comment by pdpinch** [comment]
@tasawernawaz can you review this? We'd like to cherry-pick it into the xPRO instance of open edX.

**Comment by tasawernawaz** [comment]
@pdpinch Sure, I can take a look.

**Comment by tasawernawaz** [comment]
@annagav I am getting error on `/sysadmin/gitlogs`

```
ConnectionError at /sysadmin/gitlogs
Cannot connect to database default :
[Errno 111] Connection refused
```

Do I need to export/import course(s) to fix this issue ?

**Comment by tasawernawaz** [comment]
After commenting code related to making connection with db it works fine. Not related to this PR though.

@pdpinch do you want me to created a PR against our branch `xpro/ironwood`

**Review by tasawernawaz — APPROVED** [review]

**Pull request merged**
