### PR TITLE
Enable bulk course email from env variable

### LINKED ISSUE #105: Make the enabling of instructor email configurable
See https://openedx.atlassian.net/browse/CRI-132

As an instructor, I find it confusing when a new course is created for me and I can't email my learners.

As an open edX support staff, I find it time-consuming and a distraction to have to turn on instructor emails for each course individually through the django admin.

It would be better if the the default setting for `email_enabled` were configurable by a site setting instead of hard-coded to default to False.

See https://github.com/edx/edx-platform/blob/open-release/hawthorn.2/lms/djangoapps/bulk_email/models.py#L418

Also, this conversation in Slack: https://openedx.slack.com/archives/C12M8M5AR/p1541014528004600

### PR DESCRIPTION
**Pull request by annagav**
Fix #105

Make the bulk course email feature enabled based on environment variable.

### CODE REVIEW

**Comment by pdpinch** [comment]
Can you make it a failover, i.e. check the default setting first, if it isn't there, or if it's false, check the database value?

I'm trying to find a way to make this work for edx as well as us.

**Comment by annagav** [comment]
It looks like if in django admin I go to Bulk email flags, I can add a new flag where I check `require_course_email_auth` off and that seems to enable bulk emails for all courses. Would this solve the issue?
screen shot 2018-11-28 at 9 33 55 am

**Comment by pdpinch** [comment]
The issue is that it needs to be turned on for every course, which is a big administrative burden. We just want it to default to on. 

I tried to make that clear in the issue description, but maybe a screenshot would have helped?

**Comment by annagav** [comment]
There are two different models, I think the one you are refering to is `CourseAuthorizations`, where you enailble it for each course individually. But there is also this model `BulkEmailFlags` where you set `Require course email auth` to false, and that enables bulk email for all courses.
screen shot 2018-11-28 at 9 56 48 am

**Comment by pdpinch** [comment]
I guess we should try turning that on... 

@mitodl/devops @NotoriousMKD can we try this in the new release?

**Comment by pdpinch** [comment]
@NotoriousMKD tells me this worked on the next release. 

Do you want to turn it on in production now, and then we can call it a day? Since this is a database setting, I don't think it will travel from our QA stack to our production stack. You'll need to turn it on in production -- it's up to you whether to do it now or later.

**Pull request closed without merging**
