### PR TITLE
Restricting login to only third party auth

### PR DESCRIPTION
**Pull request by annagav**
Task #148 

Restrict user login and registration to only third party authentication backend, restrict public account creation.

### CODE REVIEW

**Comment by blarghmatey** [comment]
At face value that looks like it could suit our needs, though I'm not familiar enough with the social_auth mechanism to be sure. @rhysyngsun do you have any thoughts on this?

The other item is that we would like this functionality to be placed behind a feature flag or Django setting that we can toggle through configuration.

**Comment by rhysyngsun** [comment]
From my understanding this looks correct.

**Comment by blarghmatey** [comment]
:+1:

**Comment by blarghmatey** [comment]
We can merge and test this and then circle back on tests and feature gating.

**Pull request merged**
