### PR TITLE
Return error value to students when codejail raises an exception

### LINKED ISSUE #4: When codejail raises an exception, error returned to learner is an empty string
When a custom response problem (executed by codejail) raises an exception, it should return an error that the learner can see. Instead, it returns an empty string. If this worked as expected, it would be a useful behavior as it gives the course author a way to return an error to the student without costing them a submission.

### Steps to Reproduce

1. Create an advanced problem (customresponse) with the following XML:

```
<problem display_name="Error Raising">
<script type="text/python" system_path="python_lib">

def gradeit(solution, answer):
    raise ValueError("Bad entry!")
  
</script>

  <p>Enter 1 in the box below.</p>
  
<customresponse cfn="gradeit" expect="1">
  <textline size="45" correct_answer="1" math="1"/>
</customresponse>

</problem>
```

2. As a staff member, enter a value in the input box and submit. You will get a full stack trace that ends with the exception error message, "Bad entry!"

3. As a student, enter a value in the input box and submit

### Expected Behavior

(Based on the original code) The expectation is that the learner would get a response of "Error: " followed by the error message. In this case "Error: Bad entry!"

### Actual Behavior

No error message is returned, and the learner only see "Error:"

### PR DESCRIPTION
**Pull request by pdpinch**
Fixes #4 

Fixes a bug that returned an empty string instead of the error value when a custom problem raises an exception. 

### What this PR does

Based on the code and the tests, it appears that the expectation was that the error message would be returned. However, because the error in this case is a stack trace generated by code jail, the message isn't passed all the way back. This PR makes sure that the original message is retrieved, and it also attempts to omit the stack trace (at least confusion, and possibly leaking too much information to the leaner) and limit the return to just the error message.

### CODE REVIEW

**Comment by pdpinch** [comment]
FYI @jolyonb

I still plan to look into tests

**Comment by jolyonb** [comment]
I've realized that this error reporting thing that we changed also has to deal with non-codejail errors too, where the error message has been correctly set already. So, we probably changed the wrong code. Better would be to put it in responsetypes.py by modifying these lines:
https://github.com/edx/edx-platform/blob/master/common/lib/capa/capa/responsetypes.py#L2511-L2512
Note that sys.exc_info() is already being called, and that's where the traceback object is being sourced from.

**Comment by pdpinch** [comment]
@jolyonb do you still have your test courseware? I lost it in a devstack purge.

**Comment by jolyonb** [comment]
Here you go.
````
<problem display_name="Error Raising">
<script type="text/python" system_path="python_lib">

def gradeit(solution, answer):
    raise ValueError("Bad entry!")
  
</script>

  <p>Enter 1 in the box below.</p>
  
<customresponse cfn="gradeit" expect="1">
  <textline size="45" correct_answer="1" math="1"/>
</customresponse>

</problem>
````

**Comment by pdpinch** [comment]
I took a look at the code in https://github.com/edx/edx-platform/blob/master/common/lib/capa/capa/responsetypes.py#L2511-L2512 and that looks OK to me. I think it passes the intended value of err.message to the exception fine. 

I think the problem with the original code modified by this PR was a misunderstanding of the Exception class. There is no message attribute, just argv. The string passed to the exception is argv[0]. 

One thing that I need to think about is whether and how to protect against the possibility of string that doesn't look like our stack traces.

**Comment by jolyonb** [comment]
Remember that this code also handles any errors that arise from other problem types (other than customresponse), and it shows the appropriate errors in those situations. I think there is a message attribute to the Exception class, and that's what's usually raised. However, the jailed code is only returning an argv message.

**Comment by pdpinch** [comment]
What other problem types would you recommend I look at?

**Comment by jolyonb** [comment]
The main use case I can think of is the following:
````
<problem display_name="Error Raising">
<script type="text/python" system_path="python_lib">

def gradeit(solution, answer):
    raise ValueError("Bad entry!")
  
</script>

  <p>Enter 1 in the box below.</p>
  
<customresponse cfn="gradeit" expect="1">
  <textline size="45" correct_answer="1" math="1"/>
</customresponse>

  <p>Entering "a" in the box below will be graded correct. Entering "b" will yield an error.</p>
  
  <formularesponse inline="1" samples="a@1:10#5" answer="a">
    <textline size="40" inline="1" math="1">
      <responseparam type="tolerance" default="0.01%"/>
    </textline>
  </formularesponse>  
  
</problem>
````

**Comment by pdpinch** [comment]
It looks like the relevant tests are [here](https://github.com/edx/edx-platform/blob/master/common/lib/xmodule/xmodule/tests/test_capa_module.py#L675-L701) and [here](https://github.com/edx/edx-platform/blob/master/common/lib/xmodule/xmodule/tests/test_capa_module.py#L675-L7010). 

I don't understand how they could have been passing before. I'm going to look into it further.

**Comment by jolyonb** [comment]
Those tests passed because the error message worked (in present edX code) for non-customresponse errors, and there is no test for a customresponse problem, insofar as I could tell.

**Comment by pdpinch** [comment]
I feel like I've been chasing my tail a bit, but this is working for me now with your example problem, tests are passing and I think I'll even get coverage to pass. I'm going to open a PR at edX just to see if their automated tests work.

**Comment by pdpinch** [comment]
Hmm. That passed tests, but didn't actually fix the original problem. This seems to work better.

**Comment by pdpinch** [comment]
@mitodl/devops This has been reviewed by Amir and is awaiting review at edX. Would it be possible to cherry pick it into a residential release? We're on spring break currently, so it's a convenient time.

**Comment by blarghmatey** [comment]
Yes, we can cherry pick that in for a release.

**Comment by blarghmatey** [comment]
Yes, we can get this merged and rolled out. Is there an easy way of replicating the behavior for verification purposes?

**Comment by pdpinch** [comment]
It's on the issue. I should have put in the PR as well. (we could use a PR template for this repo, I guess)

I'm happy to verify on QA.

**Comment by pdpinch** [comment]
upstream PR opened at https://github.com/edx/edx-platform/pull/14591

**Pull request closed without merging**
