### PR TITLE
Load all webpack chunks into fragments as correctly-typed resources

### PR DESCRIPTION
**Pull request by blarghmatey**
Also backporting `xmodule_django` utils module

### CODE REVIEW

**Comment by pdpinch** [comment]
Sorry, what is this doing? 

Maybe @gsidebo or @annagav can review?

**Comment by pdpinch** [comment]
Tobias tells me the commit needs some cleaning before this should be reviewed.

**Comment by blarghmatey** [comment]
Good to go

**Comment by pdpinch** [comment]
I see now that this is a cherry-pick. I don't think we need a review in this case. 

👍

**Review by pdpinch — APPROVED** [review]

**Pull request merged**
